# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('diff', models.FloatField(default=0)),
                ('price', models.FloatField()),
                ('tweet', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'RUNNING', b'Running'), (b'ENDED', b'Ended')], max_length=25)),
                ('ma1', models.PositiveSmallIntegerField()),
                ('ma2', models.PositiveSmallIntegerField()),
                ('data_range', models.CharField(default=b'3h', max_length=25)),
                ('data_group', models.CharField(default=b'1m', max_length=25)),
                ('btc_balance_at_start', models.FloatField()),
                ('euro_balance_at_start', models.FloatField()),
                ('btc_balance', models.FloatField()),
                ('euro_balance', models.FloatField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('fee', models.FloatField()),
                ('type', models.CharField(choices=[(b'BUY', b'Buy'), (b'SELL', b'Sell')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trader.Session')),
            ],
        ),
    ]
